version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      # Database connection string
      DATABASE_URL: postgresql://user:password@db:5432/goobers_db
    depends_on:
      - db

  db:
    image: postgres:16-alpine # Use an Alpine-based PostgreSQL image
    environment:
      POSTGRES_DB: goobers_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  # - ./migrations:/app/migrations
  # - db_data: /var/lib/postgresql/data
